### PR TITLE
Refactoring: reconciling schema \w Apollo Meta DB

### PR DESCRIPTION
**Pull request by bzz**
Addresses https://github.com/src-d/gemini/issues/47

First step on the way to allow hash \w Apollo and query \w Gemini

### CODE REVIEW

**Comment by bzz** [comment]
Thank you for prompt review @smacker ! 

Filed
 - https://github.com/src-d/gemini/issues/49 for code style/linter
 - https://github.com/src-d/gemini/issues/50 for code formatter

**Comment by bzz** [comment]
Thank you for prompt review @smacker ! 

Filed issues for linter/formatter support.

**Comment by smacker** [comment]
thank you so much!

**Comment by bzz** [comment]
History was re-written but only last 2 commits were actually added, to include same changes in Golang query implementation.

**Comment by bzz** [comment]
Merging, if there is no further discussion

**Pull request merged**
