### PR TITLE
Remove language filtering

### PR DESCRIPTION
**Pull request by smacker**
Based on #153 
Fix: #129

### CODE REVIEW

**Comment by bzz** [comment]
👍 Let's also take care of updating a deployment with appropriate bblfshd version, before merging this.

Otherwise we would not be able to run master on staging cluster with https://github.com/src-d/issues-infrastructure/issues/184

**Comment by smacker** [comment]
@bzz We aren't able to run to run master on staging cluster already because the new engine is in master now. And it isn't compatible with old bblfsh. This PR doesn't change it.

**Comment by bzz** [comment]
Yep, please, let's fix it and link an Infra issue in there and #154  for convenience.

**Comment by smacker** [comment]
Yes. The issue is here: https://github.com/src-d/issues-infrastructure/issues/201

But I don't see any reason to wait for it to merge this PR. Master is broken already.

**Pull request merged**
