### PR TITLE
Weighted MinHash

### PR DESCRIPTION
**Pull request by carlosms**
_Description edited: now it works, and tests are passing_

Issue #67.

Right now there is a java class, `WeightedMinHash`, based on these two implementations:
* https://github.com/ekzhu/datasketch/blob/master/datasketch/weighted_minhash.py
* https://github.com/src-d/go-license-detector/blob/master/licensedb/internal/wmh/wmh.go

If I'm not mistaken, we'll get a Compressed Sparse Row matrix from the sourced.ml lib. The current implementation takes a dense array, like the datasketch implementation. I thought it would be better to start here, and then modify it to work with sparse arrays or a sparse matrix (maybe using a lib, [like this one](https://github.com/fommil/matrix-toolkits-java/blob/master/src/main/java/no/uib/cipr/matrix/sparse/CompRowMatrix.java)).

Here's what I did to test it. I implemented similar tests to the [MinHashCuda testing](https://github.com/src-d/minhashcuda/blob/master/test.py).

There is a python script in `src/test/resources/weighted-minhash/weighted_minhash_test.py` that uses the datasketch lib to create a bunch of csv files. The scala test `WeightedMinHashSpec` reads those files to initialize the `WeightedMinHash` with the same `rs`, `lnCs`, and `betas`, eliminating any difference in the random initialization of python and java. I didn't add the the csv files to git because there are _a lot_ and they weight over 20MB.

There is a new travis configuration to run only this test, as it a bit different because it depends on python. This travis job takes some time to install all the python dependencies, maybe we could find a way to cache those.

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
Sure, I will review the code in the upcoming days!

**Comment by bzz** [comment]
@carlosms really good job! Thank you for taking care.

Sorry for these niggles, but would you also be able to provide a CI time stats before/after? 
That would help to determine if some form of travis caching would be needed as part of this PR as well.

**Comment by carlosms** [comment]
As you can see [in Travis](https://travis-ci.org/src-d/gemini/builds/358419594) (PYTHON_DEPENDENCY_TESTS) it takes about the same time as the integration tests, so the total time is not increased.

However, I know you'll appreciate the new commit 2ec46b5 I have just pushed. It removes the execution of the python minhash code, and instead a new .tar.gz file with the fixtures is stored in the repo. WeightedMinHashSpec is now tested in the main travis task, and it adds no noticeable extra time. To compare the times, take a look at [build 200](https://travis-ci.org/src-d/gemini/builds/358419594) and [build 218](https://travis-ci.org/src-d/gemini/builds/361754477).

**Comment by smacker** [comment]
@carlosms could you please rebase (there are some conflicts) and merge?

**Pull request merged**
