### PR TITLE
Add LICENCE file to tarball

### PR DESCRIPTION
**Pull request by smacker**
Fix: #76

There are only 2 external proto files, both of them are mentioned in LICENCE file already.

### CODE REVIEW

**Comment by bzz** [comment]
Nice, thank you for taking care!

The goal of this issue to enable us to make a proper source/binary releases from a legal standpoint. 

While we are at it - could you please make sure all code in the repository is:
 - either written by us (or coming from one of the src-d projects and thus is GPL3)
 - or have a license header with clear mention of it's original license + mention in LICENSE?

i.e it's not very clear about https://github.com/src-d/gemini/blob/master/src/test/resources/models_changed.py - in cases like this, to be safer, we should add a comment at the top of the file, stating it's license and where is it coming from. 

One more thing - let's add paths to files inside the codebase, that are covered by those external licenses to the https://github.com/src-d/gemini/blob/master/LICENSE#L682

```
(BSD 3 Clause) protocol buffers (https://github.com/google/protobuf)
  src/main/proto/google/protobuf/descriptor.proto

(BSD 2 Clause) gogoprotobuf (https://github.com/gogo/protobuf)
  src/main/proto/github.com/gogo/protobuf/gogoproto/gogo.proto
```

Thanks again!

**Comment by smacker** [comment]
I don't really know how this legal stuff works. Maybe we should have a meeting about it with the team so you would explain us?

About py files, they aren't part of the release, are they?

**Comment by bzz** [comment]
>  Maybe we should have a meeting about it with the team so you would explain us?

Sure, will be happy to share. Feel free to send cal invite, or we could also add it to the next retrospective agenda.

> About py files, they aren't part of the release, are they?

that's the thing - as we do not have very strict policy for publishing release artifacts defined AND we already distribute a .zip file with full source code of the project, as a part of our our [releases](https://github.com/src-d/gemini/releases/tag/v0.0.1) - they might be. 

In my experience with legal -  it's way easier to stay safe and just preemptively keep track of things, thus the request for changes.

**Comment by smacker** [comment]
> the next retrospective agenda
sounds good

**Comment by bzz** [comment]
Should be ready to merged after feedback from https://github.com/src-d/gemini/pull/97#issuecomment-381856684 is addressed

**Comment by smacker** [comment]
rebased on master, there is no more `model.py` and `model_modified.py` files in the master.
I'm moving PR in CR again. Let me know if we need to do anything else here.

**Pull request merged**
