### PR TITLE
Hotfix: make CI pass

### PR DESCRIPTION
**Pull request by bzz**
This includes
 - [x] use ScyllaDB in Docker container instead of EmbeddedCassandra in test
 - [x] run integration tests with actual Apache Spark standalone installation

Let's merge ASAP as a hotfix, as soon as CI is green.

### CODE REVIEW

**Comment by bzz** [comment]
Current CI failure is due to unable to connect to ScyllaDB

```
[info] SUITE ABORTED - CassandraSparkSpec: Failed to open native connection to Cassandra at {0.0.0.0}:9042
[info]   java.io.IOException: Failed to open native connection to Cassandra at {0.0.0.0}:9042
```

**Comment by bzz** [comment]
@dpordomingo thank you for double-checking!

The only thing is, while it works locally, somehow it can not connect to DB in container at `0.0.0.0:9042` while on CI :/

**Comment by smacker** [comment]
it's bad idea to use `0.0.0.0` when you are connecting to something. In terms of listening it usually means all interfaces. But in case of connecting it usually means invalid address. Depends on system configuration. Anyway I would recommend you to connect to 127.0.0.1 instead.

**Comment by smacker** [comment]
you may want to look at this small utility for waiting: https://github.com/jwilder/dockerize

**Comment by bzz** [comment]
@smacker thanks for the heads up! Used a simpler https://github.com/vishnubob/wait-for-it

CI would pass now, sans #4 

Merging, and moving to #4 if there is no further discussion.

**Comment by dpordomingo** [comment]
LGTM

**Pull request merged**
